package presentation.enums;

public enum SuccessType {
    SIGN_IN_SUCCESS,
    LOG_IN_SUCCESS,
    FAILURE_USER_EXISTS,
    FAILURE_PASSWORD_MISMATCH,
    FAILURE_USER_NOT_FOUND,
    FAILURE_INCORRECT_PASSWORD,
    FAILURE_PASSWORD_TOO_SHORT,
    FAILURE_MISSING_FIELDS
}
